### ISSUE TITLE
Check out my fork

### ISSUE THREAD

**Issue by Minitour** [juanpablofernandez/SwiftyOnboard#1]
Hey, really neat framework.

I refactored some of the protocols to match up with the Swift 3 syntax.
I also added a new color transitioning feature.

https://github.com/Minitour/SwiftyOnboard

Keep up the good work 😄

**Comment by juanpablofernandez** [comment]
Hey there Minitour, thank you!

I went through your fork, great changes! Especially the color transitioning feature, I really like it! 😀
I would love to integrate your changes to the main file, however I noticed you changed some other files like `SwiftyOnboardPage.swift`, `SwiftyOnboardOverlay.swift` and the Example project.

I think these changes are dispensable and would love for you to make a pull request with only the **Color Transitioning Feature** and the **Swift 3 Syntax Update**, which both belong to the `SwiftyOnboard.swift` file.

Great work! 👍
Happy coding!
>

**Comment by Minitour** [comment]
@juanpablofernandez I made changes to the UI for an app I am working on, the primary stuff I wanted you to see were the syntax and color transition effect 😄

**Comment by juanpablofernandez** [comment]
@Minitour That was my guess 😂, I think the features you added are very valuable. It would be great if you could create a new fork, only add those two features and make a pull request. 😀

**Comment by Minitour** [comment]
@juanpablofernandez I am on it 😎

**Comment by Minitour** [comment]
@juanpablofernandez Don't forget to update the example project.
cheers mate :clinking_glasses:
