### ISSUE TITLE
Scroll vertical with navigation bar

### ISSUE THREAD

**Issue by Nexmind** [juanpablofernandez/SwiftyOnboard#11]
Hello,

The scroll worked perfectly until i added a navigation controller and then a navigation bar. Now my page is scrolling vertically. 

Before navigation bar
![spotmeals presentation ios](https://cloud.githubusercontent.com/assets/16007775/26317629/7126c8e6-3f18-11e7-9d6d-a2308d2b4f2b.gif)

After navigation bar 
![spotmeals presentation ios bug](https://cloud.githubusercontent.com/assets/16007775/26317681/8fff4b62-3f18-11e7-8b53-e0e58a6f0889.gif)

Seems like the height of navigation bar is added to the scroll height of content. 

Regards,

**Comment by Nexmind** [comment]
**Quick win solution**

Solved by adding the height of the navigationBar in the height of containerView in the setupContainerView method in SwiftyOnBoard class.
``` swift
    if navigationBarIsPresent {
            var newFrame = frame
            newFrame.size.height = frame.height + 64
            self.containerView.frame = newFrame
    } else {
            self.containerView.frame = frame
    }
```
declaration
``` swift
    open var navigationBarIsPresent: Bool = false
```
set 
``` swift
    self.swiftOnBoard.navigationBarIsPresent = true
    self.swiftOnBoard.delegate = self
    self.swiftOnBoard.dataSource = self
```

**Comment by Isuru-Nanayakkara** [comment]
Thanks @Nexmind. I was experiencing this issue as well. I took your solution and expanded on it a little. Instead of hardcoding the navigation bar height and adding an extra property, I added the following extension method to retrieve the parent view controller in which this view is displayed.

```swift
private extension UIView {
    var parentController: UIViewController? {
        var parentResponder: UIResponder? = self
        while parentResponder != nil {
            parentResponder = parentResponder!.next
            if let viewController = parentResponder as? UIViewController {
                return viewController
            }
        }
        return nil
    }
}
```

After that in the `setupContainerView` method, I simply check if the parent view controller has a navigation controller and get its navigation bar's height this way.

```swift
if let navigationBar = self.parentController?.navigationController?.navigationBar {
    var newFrame = self.frame
    newFrame.size.height = self.frame.height + navigationBar.frame.height
    self.containerView.frame = newFrame
} else {
    self.containerView.frame = self.frame
}
```

Created a PR #25. If it doesn't get merged, you can still add the following to your `Podfile` if you're using CocoaPods.

```
pod 'SwiftyOnboard', :git => 'https://github.com/Isuru-Nanayakkara/SwiftyOnboard.git', :branch => 'navbar-fix'
```

**Comment by vadimue** [comment]
@Isuru-Nanayakkara hey guys,

You don't need to change source code of the library. You just need to change `automaticallyAdjustsScrollViewInsets` of UIViewController to `false`
