### ISSUE TITLE
Build fail on iOS 11/Swift 4

### ISSUE THREAD

**Issue by zacrose14** [juanpablofernandez/SwiftyOnboard#19]
Trying to use this and I'm getting a build time error from Swift Compiler and it appears some changes from Swift 3 to Swift broke part..

Argument of '#selector' refers to instance method 'didTapPageControl' that is not exposed to Objective-C

'init(colorLiteralRed:green:blue:alpha:)' is unavailable: This initializer is only meant to be used by color literals

Argument of '#selector' refers to instance method 'tappedPage()' that is not exposed to Objective-C

**Comment by adrum** [comment]
If you are using CocoaPods, you can add this to the bottom of your Podfile:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'SwiftyOnboard'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```

**Comment by zacrose14** [comment]
That fixed it for now, thanks!
