### ISSUE TITLE
Carthage installation

### ISSUE THREAD

**Issue by Domsware** [juanpablofernandez/SwiftyOnboard#5]
Please add Carthage as a way of installing SwiftyOnboard!

**Comment by TofPlay** [comment]
Hi,
Some are articles to help you: 
- [Ruthlessly Simple Dependency Management with Carthage](https://goo.gl/8AMTfw)
- [Carthage Tutorial: Getting Started](https://goo.gl/9pVzFX)
- [Making Carthage-compatible Frameworks with Swift](https://goo.gl/SzPe8j)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods](https://goo.gl/mzZ3Si) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by juanpablofernandez** [comment]
Carthage has been added :)
