### ISSUE TITLE
Delegate should be defined as weak

### ISSUE THREAD

**Issue by funkenstrahlen** [juanpablofernandez/SwiftyOnboard#6]
You should define the delegate as a weak variable to prevent memory cycles.

https://github.com/juanpablofernandez/SwiftyOnboard/blob/master/SwiftyOnboard/SwiftyOnboard.swift#L64

**Comment by juanpablofernandez** [comment]
Updated :)

**Comment by funkenstrahlen** [comment]
Great, thansk!
