### ISSUE TITLE
Minimum deployment target error

### ISSUE THREAD

**Issue by Domsware** [juanpablofernandez/SwiftyOnboard#7]
On `import SwiftyOnboard`an error occur: `Module file's minimum deployment target is iOS10.2 v10.2`.

Installation by Carthage.

**Comment by Domsware** [comment]
On` SwiftyOnboard` project, set `Deployment Target` to **9.0** for `SwiftyOnboard` target.

**Comment by Domsware** [comment]
Problem still here, after updating `SwiftyOnboard` using Carthage to 1.3.2 version.
To make it work I have to change this on the Carthage checkout folder's then create a custom build upon this modified version:

`carthage build  SwiftyOnboard --platform iOS`

**Comment by juanpablofernandez** [comment]
I noticed I missed the Deployment Target in the project file, fixed it and pushed an update. Let me know if it's fixed.

**Comment by Domsware** [comment]
OK, it's fixed.

**Comment by Domsware** [comment]
Thank you.
