### ISSUE TITLE
Continue Button for storyboard example

### ISSUE THREAD

**Issue by SirSamShaw** [juanpablofernandez/SwiftyOnboard#9]
Is there a specific reason why the continue button does not function when running the storyboard example view controller?

**Comment by juanpablofernandez** [comment]
Hey there, good catch! 

It doesn't work because there is no target attached to it, If you look that the no-storyboard example line 90-91 you'll see how the targets are setup.

**Comment by juanpablofernandez** [comment]
Fixed and updated
